//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;
use serde::{Serialize, Deserialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "album")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    /// Non-empty album name
    pub name: String,
    /// Date of album release
    pub date_published: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::album_artist_mtm::Entity")]
    AlbumArtistMtm,
    #[sea_orm(has_many = "super::song::Entity")]
    Song,
}

impl Related<super::album_artist_mtm::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumArtistMtm.def()
    }
}

impl Related<super::song::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Song.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
