//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "genre")]
pub enum Genre {
    #[sea_orm(string_value = "metal")]
    Metal,
    #[sea_orm(string_value = "classical")]
    Classical,
    #[sea_orm(string_value = "jazz")]
    Jazz,
    #[sea_orm(string_value = "pop")]
    Pop,
    #[sea_orm(string_value = "rock")]
    Rock,
}
