//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "genre")]
pub enum Genre {
    #[sea_orm(string_value = "jazz")]
    Jazz,
    #[sea_orm(string_value = "pop")]
    Pop,
    #[sea_orm(string_value = "rock")]
    Rock,
}
