//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub use super::album::Entity as Album;
pub use super::album_artist_mtm::Entity as AlbumArtistMtm;
pub use super::artist::Entity as Artist;
pub use super::song::Entity as Song;
