//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

#[cfg(not(target_family = "wasm"))]
pub use super::album::Entity as Album;
#[cfg(target_family = "wasm")]
pub use super::album::Model as Album;
#[cfg(not(target_family = "wasm"))]
pub use super::album_artist_mtm::Entity as AlbumArtistMtm;
#[cfg(target_family = "wasm")]
pub use super::album_artist_mtm::Model as AlbumArtistMtm;
#[cfg(not(target_family = "wasm"))]
pub use super::artist::Entity as Artist;
#[cfg(target_family = "wasm")]
pub use super::artist::Model as Artist;
#[cfg(not(target_family = "wasm"))]
pub use super::song::Entity as Song;
#[cfg(target_family = "wasm")]
pub use super::song::Model as Song;
